export interface NameOfAllah {
  number: number;
  name: string;
  transliteration: string;
  en: string;
}

export const ASMA_UL_HUSNA: NameOfAllah[] = [
  { number: 1, name: "الرَّحْمَنُ", transliteration: "Ar-Rahman", en: "The Beneficent" },
  { number: 2, name: "الرَّحِيمُ", transliteration: "Ar-Raheem", en: "The Merciful" },
  { number: 3, name: "الْمَلِكُ", transliteration: "Al-Malik", en: "The King / Sovereign" },
  { number: 4, name: "الْقُدُّوسُ", transliteration: "Al-Quddus", en: "The Most Holy" },
  { number: 5, name: "السَّلَامُ", transliteration: "As-Salam", en: "The Source of Peace" },
  { number: 6, name: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", en: "The Infuser of Faith" },
  { number: 7, name: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", en: "The Preserver of Safety" },
  { number: 8, name: "الْعَزِيزُ", transliteration: "Al-Aziz", en: "The All Mighty" },
  { number: 9, name: "الْجَبَّارُ", transliteration: "Al-Jabbar", en: "The Compeller" },
  { number: 10, name: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", en: "The Supreme" },
  { number: 11, name: "الْخَالِقُ", transliteration: "Al-Khaliq", en: "The Creator" },
  { number: 12, name: "الْبَارِئُ", transliteration: "Al-Bari", en: "The Evolver" },
  { number: 13, name: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", en: "The Fashioner" },
  { number: 14, name: "الْغَفَّارُ", transliteration: "Al-Ghaffar", en: "The Constant Forgiver" },
  { number: 15, name: "الْقَهَّارُ", transliteration: "Al-Qahhar", en: "The All-Prevailing One" },
  { number: 16, name: "الْوَهَّابُ", transliteration: "Al-Wahhab", en: "The Supreme Bestower" },
  { number: 17, name: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", en: "The Provider" },
  { number: 18, name: "الْفَتَّاحُ", transliteration: "Al-Fattah", en: "The Supreme Solver" },
  { number: 19, name: "الْعَلِيمُ", transliteration: "Al-Alim", en: "The All-Knowing" },
  { number: 20, name: "الْقَابِضُ", transliteration: "Al-Qabid", en: "The Withholder" },
  { number: 21, name: "الْبَاسِطُ", transliteration: "Al-Basit", en: "The Extender" },
  { number: 22, name: "الْخَافِضُ", transliteration: "Al-Khafid", en: "The Reducer" },
  { number: 23, name: "الرَّافِعُ", transliteration: "Ar-Rafi", en: "The Exalter" },
  { number: 24, name: "الْمُعِزُّ", transliteration: "Al-Mu'izz", en: "The Honourer-Bestower" },
  { number: 25, name: "الْمُذِلُّ", transliteration: "Al-Muzil", en: "The Abaser" },
  { number: 26, name: "السَّمِيعُ", transliteration: "As-Sami", en: "The All-Hearing" },
  { number: 27, name: "الْبَصِيرُ", transliteration: "Al-Basir", en: "The All-Seeing" },
  { number: 28, name: "الْحَكَمُ", transliteration: "Al-Hakam", en: "The Impartial Judge" },
  { number: 29, name: "الْعَدْلُ", transliteration: "Al-Adl", en: "The Utterly Just" },
  { number: 30, name: "اللَّطِيفُ", transliteration: "Al-Latif", en: "The Subtle One" },
  { number: 31, name: "الْخَبِيرُ", transliteration: "Al-Khabir", en: "The All-Aware" },
  { number: 32, name: "الْحَلِيمُ", transliteration: "Al-Halim", en: "The Forbearing" },
  { number: 33, name: "الْعَظِيمُ", transliteration: "Al-Azim", en: "The Magnificent" },
  { number: 34, name: "الْغَفُورُ", transliteration: "Al-Ghafur", en: "The Great Forgiver" },
  { number: 35, name: "الشَّكُورُ", transliteration: "Ash-Shakur", en: "The Most Appreciative" },
  { number: 36, name: "الْعَلِيُّ", transliteration: "Al-Ali", en: "The Most High" },
  { number: 37, name: "الْكَبِيرُ", transliteration: "Al-Kabir", en: "The Most Great" },
  { number: 38, name: "الْحَفِيظُ", transliteration: "Al-Hafiz", en: "The Preserver" },
  { number: 39, name: "الْمُقِيتُ", transliteration: "Al-Muqit", en: "The Sustainer" },
  { number: 40, name: "الْحَسِيبُ", transliteration: "Al-Hasib", en: "The Reckoner" },
  { number: 41, name: "الْجَلِيلُ", transliteration: "Al-Jalil", en: "The Majestic" },
  { number: 42, name: "الْكَرِيمُ", transliteration: "Al-Karim", en: "The Most Generous" },
  { number: 43, name: "الرَّقِيبُ", transliteration: "Ar-Raqib", en: "The Watchful" },
  { number: 44, name: "الْمُجِيبُ", transliteration: "Al-Mujib", en: "The Responsive One" },
  { number: 45, name: "الْوَاسِعُ", transliteration: "Al-Wasi", en: "The All-Encompassing" },
  { number: 46, name: "الْحَكِيمُ", transliteration: "Al-Hakim", en: "The All-Wise" },
  { number: 47, name: "الْوَدُودُ", transliteration: "Al-Wadud", en: "The Most Loving" },
  { number: 48, name: "الْمَجِيدُ", transliteration: "Al-Majid", en: "The Glorious" },
  { number: 49, name: "الْبَاعِثُ", transliteration: "Al-Ba'ith", en: "The Resurrector" },
  { number: 50, name: "الشَّهِيدُ", transliteration: "Ash-Shahid", en: "The Witness" },
  { number: 51, name: "الْحَقُّ", transliteration: "Al-Haqq", en: "The Absolute Truth" },
  { number: 52, name: "الْوَكِيلُ", transliteration: "Al-Wakil", en: "The Trustee" },
  { number: 53, name: "الْقَوِيُّ", transliteration: "Al-Qawi", en: "The All-Strong" },
  { number: 54, name: "الْمَتِينُ", transliteration: "Al-Matin", en: "The Firm One" },
  { number: 55, name: "الْوَلِيُّ", transliteration: "Al-Wali", en: "The Protecting Friend" },
  { number: 56, name: "الْحَمِيدُ", transliteration: "Al-Hamid", en: "The Praiseworthy" },
  { number: 57, name: "الْمُحْصِي", transliteration: "Al-Muhsi", en: "The All-Enumerating" },
  { number: 58, name: "الْمُبْدِئُ", transliteration: "Al-Mubdi", en: "The Originator" },
  { number: 59, name: "الْمُعِيدُ", transliteration: "Al-Mu'id", en: "The Restorer" },
  { number: 60, name: "الْمُحْيِي", transliteration: "Al-Muhyi", en: "The Giver of Life" },
  { number: 61, name: "الْمُمِيتُ", transliteration: "Al-Mumit", en: "The Creator of Death" },
  { number: 62, name: "الْحَيُّ", transliteration: "Al-Hayy", en: "The Ever-Living" },
  { number: 63, name: "الْقَيُّومُ", transliteration: "Al-Qayyum", en: "The Sustainer of Existence" },
  { number: 64, name: "الْوَاجِدُ", transliteration: "Al-Wajid", en: "The Finder" },
  { number: 65, name: "الْمَاجِدُ", transliteration: "Al-Majid", en: "The Noble" },
  { number: 66, name: "الْوَاحِدُ", transliteration: "Al-Wahid", en: "The Unique" },
  { number: 67, name: "الْأَحَد", transliteration: "Al-Ahad", en: "The One" },
  { number: 68, name: "الصَّمَدُ", transliteration: "As-Samad", en: "The Eternal" },
  { number: 69, name: "الْقَادِرُ", transliteration: "Al-Qadir", en: "The All-Powerful" },
  { number: 70, name: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", en: "The Creator of All Power" },
  { number: 71, name: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", en: "The Expediter" },
  { number: 72, name: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", en: "The Delayer" },
  { number: 73, name: "الْأَوَّلُ", transliteration: "Al-Awwal", en: "The First" },
  { number: 74, name: "الْآخِرُ", transliteration: "Al-Akhir", en: "The Last" },
  { number: 75, name: "الظَّاهِرُ", transliteration: "Az-Zahir", en: "The Manifest" },
  { number: 76, name: "الْبَاطِنُ", transliteration: "Al-Batin", en: "The Hidden" },
  { number: 77, name: "الْوَالِي", transliteration: "Al-Wali", en: "The Governor" },
  { number: 78, name: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", en: "The Most Exalted" },
  { number: 79, name: "الْبَرُّ", transliteration: "Al-Barr", en: "The Source of Goodness" },
  { number: 80, name: "التَّوَّابُ", transliteration: "At-Tawwab", en: "The Ever-Pardoning" },
  { number: 81, name: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", en: "The Avenger" },
  { number: 82, name: "الْعَفُوُّ", transliteration: "Al-Afuww", en: "The Pardoner" },
  { number: 83, name: "الرَّءُوفُ", transliteration: "Ar-Ra'uf", en: "The Most Kind" },
  { number: 84, name: "مَالِكُ الْمُلْكِ", transliteration: "Malik-ul-Mulk", en: "Master of the Kingdom" },
  { number: 85, name: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Zul-Jalal wal-Ikram", en: "Lord of Majesty and Bounty" },
  { number: 86, name: "الْمُقْسِطُ", transliteration: "Al-Muqsit", en: "The Equitable" },
  { number: 87, name: "الْجَامِعُ", transliteration: "Al-Jami", en: "The Gatherer" },
  { number: 88, name: "الْغَنِيُّ", transliteration: "Al-Ghani", en: "The Self-Sufficient" },
  { number: 89, name: "الْمُغْنِي", transliteration: "Al-Mughni", en: "The Enricher" },
  { number: 90, name: "الْمَانِعُ", transliteration: "Al-Mani", en: "The Withholder" },
  { number: 91, name: "الضَّارُّ", transliteration: "Ad-Darr", en: "The Distresser" },
  { number: 92, name: "النَّافِعُ", transliteration: "An-Nafi", en: "The Propitious" },
  { number: 93, name: "النُّورُ", transliteration: "An-Nur", en: "The Light" },
  { number: 94, name: "الْهَادِي", transliteration: "Al-Hadi", en: "The Guide" },
  { number: 95, name: "الْبَدِيعُ", transliteration: "Al-Badi", en: "The Incomparable" },
  { number: 96, name: "الْبَاقِي", transliteration: "Al-Baqi", en: "The Ever-Enduring" },
  { number: 97, name: "الْوَارِثُ", transliteration: "Al-Warith", en: "The Inheritor" },
  { number: 98, name: "الرَّشِيدُ", transliteration: "Ar-Rashid", en: "The Guide to the Right Path" },
  { number: 99, name: "الصَّبُورُ", transliteration: "As-Sabur", en: "The Patient" }
];
